# Uncomment this line to define a global platform for your project
#  platform :ios, “7.0”

platform :ios, '7.0'
pod 'AFNetworking','~> 2.2'

pod 'MBProgressHUD','~> 0.8'
pod 'DejalActivityView','~>1.2'


